---
# tasks file for audit

- name: Install audit packages
  package:
    name: "{{ audit_packages }}"
    state: present
    update_cache: true

- name: Enable auditd service
  service:
    name: auditd
    enabled: true
    state: started
  when:
    - ansible_virtualization_type not in _container_types
    - ansible_connection not in _container_types


# Now determine if the line have already audit=1
- name: Check if audit=1 is present
  lineinfile:
    path: /etc/default/grub
    regexp: '^\s*GRUB_CMDLINE_LINUX.*audit=1'
    state: absent
  check_mode: true
  changed_when: false
  register: audit_exist
  when:
    - ansible_virtualization_type not in _container_types
    - ansible_connection not in _container_types

- name: Error message
  fail:
    msg: ">>>> ERROR: Use grub role to add audit=1 option into cmdline <<<<"
  when:
    - ansible_virtualization_type not in _container_types
    - ansible_connection not in _container_types
    - not audit_exist.found

# Now determine if the line have already audit_backlog_limit
- name: Check if audit_backlog_limit is present
  lineinfile:
    path: /etc/default/grub
    regexp: '^\s*GRUB_CMDLINE_LINUX.*audit_backlog_limit=.+'
    state: absent
  check_mode: true
  changed_when: false
  register: audit_exist
  when:
    - ansible_virtualization_type not in _container_types
    - ansible_connection not in _container_types

- name: Error message
  fail:
    msg: ">>>> ERROR: Use grub role to add audit_backlog_limit option into cmdline <<<<"
  when:
    - ansible_virtualization_type not in _container_types
    - ansible_connection not in _container_types
    - not audit_exist.found

- name: Get min_uid for the system
  shell: |
    set -o pipefail
    grep -E "^UID_MIN\s" /etc/login.defs | awk '{ print $2 }'
  args:
    executable: /bin/bash
  register: audit_uid_min_cmd
  changed_when: false

- name: Set audit_uid_min variable with the result of last task
  set_fact:
    audit_uid_min: "{{ audit_uid_min_cmd.stdout | default(1000, true) }}"

- name: "Apply audit configuration settings (true/false values)"
  ansible.builtin.lineinfile:
    path: "{{ audit_config_path }}"
    regexp: "^{{ _audit_vars[item] }}[ ]+=.*"
    line: "{{ _audit_vars[item] }} = {{ 'yes' if lookup('vars', item) else 'no' }}"
    mode: '0644'
  when: lookup('vars', item, default='undefined') != 'undefined'
  loop:
    - audit_local_events
    - audit_write_logs
    - audit_verify_email
    - audit_use_libwrap
    - audit_distribute_network
  notify: reload auditd

- name: Apply audit configuration settings
  ansible.builtin.lineinfile:
    path: "{{ audit_config_path }}"
    regexp: "^{{ _audit_vars[item] }}[ ]+=.*"
    line: "{{ _audit_vars[item] }} = {{ lookup('vars', item) }}"
    mode: '0644'
  when: lookup('vars', item, default='undefined') != 'undefined'
  loop:
    - audit_log_file
    - audit_log_format
    - audit_log_group
    - audit_priority_boost
    - audit_flush
    - audit_freq
    - audit_num_logs
    - audit_name_format
    - audit_name
    - audit_max_log_file
    - audit_max_log_file_action
    - audit_action_mail_acct
    - audit_space_left
    - audit_space_left_action
    - audit_admin_space_left
    - audit_admin_space_left_action
    - audit_disk_full_action
    - audit_disk_error_action
    - audit_tcp_listen_port
    - audit_tcp_listen_queue
    - audit_tcp_max_per_addr
    - audit_tcp_client_ports
    - audit_tcp_client_max_idle
    - audit_transport
    - audit_krb5_principal
    - audit_krb5_key_file
    - audit_q_depth
    - audit_overflow_action
    - audit_plugin_dir
  notify: reload auditd

- name: Ensure audit rules are configured properly
  template:
    dest: "{{ audit_rulesd_path }}/{{ item }}"
    src: "{{ item }}"
    owner: root
    group: root
    mode: 0600
    force: "{{ force_overwrite_audit | default(false) }}"
  notify: reload auditd
  loop: "{{ audit_rules_files | default([]) }}"

- name: Ensure audit configuration is immutable
  copy:
    dest: "{{ audit_rulesd_path }}/99-finalize.rules"
    content: |

      -e 2

    owner: root
    group: root
    mode: 0600
  notify: reload auditd
