---
- name: Converge
  hosts: all
  vars:
    audit_rules_files:
      - 01-init.rules
      - 10-self-audit.rules
      - 20-filters.rules
      - 30-kernel.rules
      - 40-identity.rules
      - 40-login.rules
      - 40-mount.rules
      - 40-stunnel.rules
      - 40-swap.rules
      - 40-time.rules
      - 50-cron.rules
      - 50-dac.rules
      - 50-hostname.rules
      - 50-ip-connections.rules
      - 50-network.rules
      - 50-pkg-manager.rules
      - 50-remote-shell.rules
      - 50-sudoers.rules
      - 50-system-libs.rules
      - 50-system-startup.rules
      - 55-privileged.rules
      - 60-mail.rules
      - 60-pam.rules
      - 60-sshd.rules
      - 60-systemd.rules
      - 70-access.rules
      - 70-mac-policy.rules
      - 70-power-state.rules
      - 70-sessions.rules
      - 70-shell-profiles.rules
      - 80-data-compression.rules
      - 80-network.rules
      - 80-privilege-abuse.rules
      - 80-reconnaissance.rules
      - 80-socket-creation.rules
      - 80-suspicious.rules
      - 80-suspicious-shells.rules
      - 80-virtualization.rules
      - 90-cred-in-files.rules
      - 90-IPC.rules
      - 90-root-exec.rules
      - 90-special-sw.rules
      - 95-32bit-api-exploitation.rules
  pre_tasks:
#    - name: update RedHat systems running yum
#      ansible.builtin.yum:
#        state: latest
#        name: '*'
#      when: ansible_pkg_mgr in ['yum', 'dnf']

    - name: Update Ubuntu/Debian systems
      ansible.builtin.apt:
#        upgrade: dist
        update_cache: true
        cache_valid_time: 3600
      when: ansible_pkg_mgr == "apt"

    - name: Make sure some packages are installed
      ansible.builtin.package:
        name:
          - sudo
          - vim
        state: latest
  roles:
    - role: guidugli.audit
